# -*- coding: utf-8 -*-
class States:
    AWAIT_ACTIVATION_CODE = 1
    AWAIT_REGISTER_NAME = 2
    AWAIT_REGISTER_PHONE = 3
    AWAIT_REGISTER_AGE = 4
    AWAIT_REGISTER_CITY = 5
    AWAIT_EMAIL = 6
    AWAIT_APP_PASSWORD = 7
    AWAIT_LANG_CONFIRM = 8
    JOB_PREFS_BROWSE = 9
    JOB_PREFS_SEARCH = 10
    # أدمن
    ADMIN_AWAIT_CODES = 20
    ADMIN_AWAIT_JOB_TITLE = 21
    ADMIN_AWAIT_JOB_DESC = 22
    ADMIN_AWAIT_JOB_COMPANY = 23
    ADMIN_AWAIT_JOB_EMAIL = 28
    ADMIN_AWAIT_JOB_SPEC = 29      # اختيار التخصصات عبر أزرار inline
    ADMIN_AWAIT_ANN_TITLE = 25
    ADMIN_AWAIT_ANN_BODY = 26
    ADMIN_AWAIT_ANN_IMAGE = 30
    ADMIN_AWAIT_ANN_DURATION = 31
    ADMIN_AWAIT_ANN_REPEAT = 32
    ADMIN_AWAIT_SINGLE_CODE = 27
